### PR TITLE
v0.0.1

### PR DESCRIPTION
**Pull request by HinaKaze**
# v0.0.1
**Added**
- package structure of kagami
- default node picker
- default node namer
- default node register
- /register http api
- CHANGELOG.md

**Changed**
- refine var name according to term doc : https://about.kyonko.moe/kyonko-network-impl-details/

### CODE REVIEW

**Comment by HinaKaze** [comment]
@SakuraSa pls review

**Comment by HinaKaze** [comment]
#2

**Review by SakuraSa — CHANGES_REQUESTED** [review]
Looks good to me.

**Comment by HinaKaze** [comment]
@SakuraSa 
i will merge this pr to master. 
the network layer code still not implemented , can u complete it.
btw , i received notification from email , but i'm not subscribe my email ,oops.
i think , work day ( mon - fri ) is a good time to coding , discussing pr asynchronized.
rest day (sat - sun) is better to discussion feature , proposal.

**Pull request merged**
